// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ5wlLksfthecLpRn5j2RZFpFQ3BCsCyE',
    appId: '1:292951260141:web:c8ff6eda6dd7a07d8f05e4',
    messagingSenderId: '292951260141',
    projectId: 'let-s-chat-44e8e',
    authDomain: 'let-s-chat-44e8e.firebaseapp.com',
    storageBucket: 'let-s-chat-44e8e.appspot.com',
    measurementId: 'G-KC2C4B25KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf3dASabkozo4ZcUdJ8DylOROWkH9-fto',
    appId: '1:292951260141:android:25e14aead8a8e6f48f05e4',
    messagingSenderId: '292951260141',
    projectId: 'let-s-chat-44e8e',
    storageBucket: 'let-s-chat-44e8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwUAZz8luTBo8jI6KSKmggbuFj9fS9Thg',
    appId: '1:292951260141:ios:831e474605b3e3048f05e4',
    messagingSenderId: '292951260141',
    projectId: 'let-s-chat-44e8e',
    storageBucket: 'let-s-chat-44e8e.appspot.com',
    iosBundleId: 'com.example.letsChat',
  );
}
